### ISSUE TITLE
Query Strings do not trigger update & are missing in page object

### ISSUE THREAD

**Issue by akowi-sknobloch** [nanostores/router#11]
I've noticed that the router ignores changes to the query strings.
When calling the same path with other query Strings no State update is triggered.

When the router detects a change, it does not return the Query strings.

I have created a minimal example: 
https://github.com/akowi-sknobloch/nanostores-router-query-string-error

**Comment by akowi-sknobloch** [comment]
I think having the router should react to query changes.
Maybe as an opt-in feature so everyone can decide if they want to handle query changes themself.

I have a current Project in it's early phase for wich this feature would be very nice.

**Comment by ai** [comment]
> I think having the router should react to query changes.

Highly depends on the project.

Often path means the page and query use used for the page’s parameters. For instance, `/search?query=nanostore`.

Having query inside route will be very unuseful for this use case.

What is your use case? What URLs do you plan to have?

**Comment by akowi-sknobloch** [comment]
> Highly depends on the project.

I agree with that.
That's why i suggested adding a opt-in parameter for that feature.

One of my Project's routes looks like this:
`/p/<seo_optimized_product_name>-12393?product=32095&article=92776&variation=12086`

That page heavily depends on query strings for displaying different variations of a Product.

Other pages will have filtering and sorting via query strings (not yet implemented).

**Comment by ai** [comment]
Got it. Wait for a weekend. I will try to find a solution.

**Comment by ai** [comment]
Option was added dccfeb5

Note, that the search params options is critical. Router use search query as a string.

**Comment by ai** [comment]
I also added `searchParams` store https://github.com/nanostores/router#search-query-routing

The fix was released in 0.4.
