### ISSUE TITLE
Expected 2 arguments, but got 3

### ISSUE THREAD

**Issue by rapitkan** [nanostores/router#17]
<img width="815" alt="Screenshot 2023-03-16 at 14 44 29" src="https://user-images.githubusercontent.com/2033731/225621888-3b44411d-ed91-42b7-833c-ac1b8f543360.png">

Problem: redirectPage function complains when user is trying to give three parameters for it.

**Comment by ai** [comment]
Can you show your routes?

**Comment by rapitkan** [comment]
Hi. I was able to resolve the issue by myself. Route configuration was defined without `as const`. I added that and the error vanished. Your question about seeing the routes was helpful. Thanks.
