### ISSUE TITLE
Problem: getPagePath complains about the third parameter

### ISSUE THREAD

**Issue by rapitkan** [nanostores/router#18]
<img width="869" alt="Screenshot 2023-03-16 at 14 52 29" src="https://user-images.githubusercontent.com/2033731/225622677-45bedb93-c4ea-43ec-9480-e0bb25b20c57.png">

Problem: getPagePath function complains when user tries to give the third parameter.

#typescript

**Comment by ai** [comment]
Csn you show your routes?

**Comment by rapitkan** [comment]
Hi. I was able to resolve the issue by myself. Route configuration was defined without `as const`. I added that and the error vanished. Your question about seeing the routes was helpful. Thanks.
