### ISSUE TITLE
Unable to handle arrays in searchParams

### ISSUE THREAD

**Issue by fprl** [nanostores/router#26]
Hello there, I have a few questions about this great library:

1. Is it possible to handle arrays in searchParams? I tried `searchParams.open({'filters[regions]': '1,2,3'})` but I get `?filters%5Bregions%5D%5B%5D=2%2C5%2C4%2C1`, so when using `decodeURI('?filters[regions][]=2%2C5%2C4%2C1')` I get `?filters[regions][]=2%2C5%2C4%2C1`
2. Also, its not possible to manage arrays like many sites/api do: `filters[regions]=1&filters[regions]=2`
3. How would you remove `searchParams`? for example I don't want persons=0 to be in the URL, I would remove the searchParam in that case

Thanks.

**Comment by ai** [comment]
Send PR please if you know how to add it without bloating JS bundle (or you can copy-paste store and extend it for your needs, they are very simple inside, don't afraid to write your own)

**Comment by fprl** [comment]
Hi Andrey, thanks. I was confused because `decodeURI` doesn't do this but URLSearchParams.toString() yes:
https://github.com/nanostores/router/blob/83699283a01f319e080a97fb1f2eef6801af5349/index.js#L162C56-L162C56

Will do that!

Regards
