### ISSUE TITLE
Add ability to clear route history

### ISSUE THREAD

**Issue by ivan-suhorukov** [nanostores/router#28]
Hi! I want to clear the routes history on user logout. Is there a way to do this?

Now, when i logout, my app shows only login page. But when i press "back" browser button on that page it continues to change url in browser. How can i prevent this behaviour and leave only "login" route?

Thanks!

**Comment by ivan-suhorukov** [comment]
Oh, sorry, i did miss the redirect function :(

**Comment by ai** [comment]
Do we have the API for that in History API?

**Comment by ivan-suhorukov** [comment]
Oh, we have not. You are right. It seems impossible now, so i close the issue.
