### ISSUE TITLE
Hash routing

### ISSUE THREAD

**Issue by AndreiEres** [nanostores/router#3]
Developing chrome extension I realised that I can't use nanostores for routing because it doesn't use hash.

Are there any plans to add hash routing?

**Comment by AndreiEres** [comment]
> Do you have an idea of what it should do?

I think it should parse url params `#/pages/:page`.

**Comment by ai** [comment]
> I think it should parse url params #/pages/:page.

It will not fit my case, when I have list of popups. We can use a different hash routers for different use cases. Like `createHashPageRouter` and `createHashListRouter`.

BTW, why do you use `#/…` page routing instead of using the real URL?

**Comment by AndreiEres** [comment]
> It will not fit my case, when I have list of popups. We can use a different hash routers for different use cases. Like `createHashPageRouter` and `createHashListRouter`.

What do you mean? How it looks?

In my case I just added new store subscribed to hash changes and parsed last param from url. It's quite enough for small cases.



> BTW, why do you use `#/…` page routing instead of using the real URL?

Hm, I think it doesn't work on extension popup.

**Comment by ai** [comment]
> What do you mean? How it looks?

I use hash to store data about current opened popups like `#userPopup:userId,confirm:delete:userId`.

> In my case I just added new store subscribed to hash changes and parsed last param from url. It's quite enough for small cases

Yeap, I like the idea.

```js
createHashStore(hash => parseHash(hash))
```

It could work for both our cases.

**Comment by JulianCataldo** [comment]
Hello there,

I've not digged yet into the code regarding encode/decodeURI stuff, and maybe I should open a separate issue for this?

I put this here because my need it's kind of interlaced with this present issue.
Would be cool to have a catch-all params like:

```js
const routes = {
  home: "/home",
  // content: "/content",
  // content: "/content",
  content: "/content/:path?",
} as const;
```

```sh
# Currently:
http://localhost:5173/content/%2Ftest_repo_1%2Fmain%2Fdocs%2Fllasslaa1683544785369.md

# Would like:
http://localhost:5173/content/test_repo_1/main/docs/llasslaa1683544785369.md

# Or maybe with opt-in hash routing, if possible?:
http://localhost:5173/content#/test_repo_1/main/docs/llasslaa1683544785369.md
```

I'm not sure about allowed characters inside URL, after hash or search params…
Rules seems pretty wild.

Inspiration: [Stoplight Elements](https://docs.stoplight.io/docs/elements/a71d7fcfefcd6-elements-in-html) or Redoc Redocly are offering all sort of routing options (dynamic path segments or hash).

Thanks for hearing me!

**Comment by ai** [comment]
@JulianCataldo yes, it should be a separated issue (and very likely that I will need a PR for this)

**Comment by jqueryisamonad** [comment]
> BTW, why do you use `#/…` page routing instead of using the real URL?

I embed small svelte apps in php pages. In this case I just can't use real URLs. It would be great to have a fully functional hash page router.

No pressure on contributors, just describing one more use case

**Comment by ai** [comment]
Nano Stores Router 0.16 was released with `router.get().hash`

It is not extactly pattern matching, but it can be added with `computed()`.

**Comment by JulianCataldo** [comment]
Very nice! Thank you @ai for you awesome work ❤️
